### PR TITLE
Add #soft_delete method

### PR DESCRIPTION
**Pull request by Aryk**
I noticed there was no activity on this gem, so just adding this here, maybe someone else will want to fork my branch or actually merge this into the main repo (or a future new repo).

Two main changes here:

 * From @halostatue, I'm incorporating his support for validating unique with `:paranoid => true`. It's an opt-in feature, so I figured why not include it.
 * I didn't like that destroy was being overwritten. What if you want to soft delete under a certain condition but then destroy on another? This plugin has no way to override that behavior. By default this plugin has no side effects in your code, which I think is a "safer" direction.
 * Added dataset methods to soft delete records. So now you can do school.students_dataset.soft_delete and soft delete them from your school. 😃

### CODE REVIEW

**Comment by sdepold** [comment]
@Aryk I just invited you to the repo. Please let me know what else you need :)

**Comment by Aryk** [comment]
Thanks @sdepold. How do I actually release it to rubygems?

**Comment by sdepold** [comment]
@Aryk I'll need your account on rubygems.org

**Comment by Aryk** [comment]
aryk.grosz@gmail.com

@sdepold do you need anything else?

**Comment by sdepold** [comment]
@Aryk Just added you to rubygems. Have fun!

**Comment by Aryk** [comment]
Thanks @sdepold !

**Comment by Aryk** [comment]
@sdepold - just throwing it out there, if you want to transfer this repo over to me in case you want to clean up your list of repos, that would be ok with me as well.

**Pull request merged**
